### ISSUE TITLE
Suspected Worker<>Tracer Broken Integration

### ISSUE THREAD

**Issue by alongir** [kubeshark/tracer#14]
When running a simple experiment:
1. Use the following containers:
- https://github.com/kubeshark/sock-shop-demo/tree/master/additions/outbound-tls-golang
- https://github.com/kubeshark/sock-shop-demo/tree/master/additions/outbound-tls-openssl

Using the following manifests:
- deploy/kubernetes/manifests/00-sock-shop-ns.yaml
- deploy/kubernetes/manifests/extras/46-mizutest-outbound-tls-openssl-dep.yaml
- deploy/kubernetes/manifests/extras/47-mizutest-outbound-tls-openssl-svc.yaml
- deploy/kubernetes/manifests/extras/52-mizutest-outbound-tls-golang-dep.yaml
- deploy/kubernetes/manifests/extras/53-mizutest-outbound-tls-golang-svc.yaml

2.  Ensure the tracer generates the right information from both images
3. Ensure the Worker receives and process the information from the Tracer.

**Comment by iluxa** [comment]
Should be retested after https://github.com/kubeshark/tracer/issues/15 get fixed

**Comment by alongir** [comment]
Take also a look here: https://github.com/kubeshark/tracer/pull/12 It may be of help

**Comment by alongir** [comment]
Replaced with: https://github.com/kubeshark/tracer/issues/25
