### ISSUE TITLE
Cgroups V2 support

### ISSUE THREAD

**Issue by alongir** [kubeshark/tracer#20]
The following was reporteda sa bug.
We need to ensure we support `cgroups v2 on premise with RHEL 9`

![Image](https://github.com/kubeshark/tracer/assets/1990761/fa469162-f198-49dd-b2b5-67ddb53e1159)

**Comment by iluxa** [comment]
It would be nice to have version information, the bug looks like about lacking of permissions (`SYS_RESOURCE`)
