### ISSUE TITLE
-cbuf doesn't show payload

### ISSUE THREAD

**Issue by alongir** [kubeshark/tracer#30]
While I see traffic on the dashboard, this is what I see when I use `cbuf`:
```yaml
/app # cat data/ip-192-168-19-177.us-west-1.compute.internal/tls_last.pcap 
?ò?/app # 
```

**Comment by iluxa** [comment]
@alongir This behavior is expected in case of unix socket is in use.
`cbuf` was developed to only debug `tls.pcap` pipe only
The idea is to have everything(limited by last packets) in `cbuf` which was written to `tls.pcap`
