### ISSUE TITLE
TLS packet drop

### ISSUE THREAD

**Issue by alongir** [kubeshark/tracer#47]
Can we take a look at the TLS packet drop and see if in fact we drop packets? If we do, let's solve it. If we don't can we true up the counters?

![Image](https://github.com/kubeshark/tracer/assets/1990761/bc2187a7-712e-4eef-9a32-25ba9d0cad26)

**Comment by iluxa** [comment]
The issue must be on the worker side, it shows how worker consumes packets from tracer
