### ISSUE TITLE
Ensure that the Tracer functions well post recent changes related to pod targeting

### ISSUE THREAD

**Issue by alongir** [kubeshark/tracer#66]
Recent pod targeting related changed may have impact the Tracer functionality. Can you please go over and ensure:
1. In case of AF-PACKET use, the tracer adheres to the pod targeting rules (including the BPF override).
2. In case of eBPF, functionality is supported.

If you recall there were changes related to:
- BPF expression
- BPF override
- IP extraction in case of multiple IFCs.

**Comment by alongir** [comment]
@iluxa there's some new code related to the BPF ovveride done via the UI that aren't in the Tracer. 
Can you take a look at the code added to the Worker here: https://github.com/kubeshark/worker/pull/145/files
As you can see there's the BPF expression in the config map and it should override any existing pod targeting rules.
I started doing this, but realized it's above my skillset. I started here: https://github.com/kubeshark/tracer/pull/67 (feel free to continue or to delete/close this PR).
Without this code and dynamic change doesn't impact the Tracer. 
Once you complete these Tracer changes, can you update the Worker PR to use the latest version of the Tracer?
Thanks!

**Comment by alongir** [comment]
If this change doesn't apply to the Tracer as it uses eBPF and not BPF, ignore this request. Just let me know.

**Comment by iluxa** [comment]
@alongir  BPF override can not be applied to tracer, because there is no mechanism to set BPF filter in it.
Tracer has pod targeting by nature: for TLS it discovering processes only within targeting pods, for eBPF packet capture it attaches eBPF programs to cgroups related to pods.

**Comment by alongir** [comment]
Makes perfect sense. I realized this after writing the comment. Thanks!
